//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.5466
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hoteles.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=JAVIER-PC\\SQLEXPRESS2008;Initial Catalog=hotel;Integrated Security=Tr" +
            "ue")]
        public string hotelConnectionString {
            get {
                return ((string)(this["hotelConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("resources/LogoHotel.png")]
        public string Logo {
            get {
                return ((string)(this["Logo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("resources/impTemp.txt")]
        public string archImprimir {
            get {
                return ((string)(this["archImprimir"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fecha: ##FECHA Hora: ##HORA\\r\\nNro.Ticket: ##NRO\\r\\n-----------------------------" +
            "------\\r\\nNro.Habitacion: ##HAB\\r\\n-----------------------------------\\r\\nCant  " +
            "Articulo              Precio\\r\\n-----------------------------------\\r\\n")]
        public string ticketCocina {
            get {
                return ((string)(this["ticketCocina"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
          ****************************************************************************************************************************
          Conserje:##conserjeId   ##conserjeNm            === Arqueo de caja ===                Fecha: ##fecha   Hora:##hora
          ****************************************************************************************************************************

                                           ____________________ FACTURADO _________________      ___________ CAJA ___________
          Nro  HAB  Desde  Hasta   Socio   Turnos     Extras     Bar     Descuento    Total      Efectivo   Tarjeta  	  gastos
          ----------------------------------------------------------------------------------------------------------------------r\n")]
        public string planillaCierre {
            get {
                return ((string)(this["planillaCierre"]));
            }
        }
    }
}
