//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.5466
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hoteles.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("resources/LogoHotel.png")]
        public string Logo {
            get {
                return ((string)(this["Logo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fecha: ##FECHA Hora: ##HORA\\r\\nNro.Ticket: ##NRO\\r\\n-----------------------------" +
            "------\\r\\nNro.Habitacion: ##HAB\\r\\n-----------------------------------\\r\\nCant  " +
            "Articulo              Precio\\r\\n-----------------------------------\\r\\n")]
        public string ticketCocina {
            get {
                return ((string)(this["ticketCocina"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost\\SQLEXPRESS2008;Initial Catalog=hotel;Integrated Security=Tr" +
            "ue")]
        public string hotelConnectionString {
            get {
                return ((string)(this["hotelConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("impTemp.txt")]
        public string archImprimir {
            get {
                return ((string)(this["archImprimir"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
*********************************************************************************************************************
Conserje:##conserjeId##conserjeNm        === Arqueo de Caja - Nro:##nroArq ===      Fecha: ##fecha   Hora:##hora
*********************************************************************************************************************

                                   ____________________ FACTURADO _______________     ___________ CAJA ____________
Nro  HAB  Desde  Hasta    Socio    Turnos     Extras     Bar     Desc       Total     Efectivo   Tarjeta     Gastos
-------------------------------------------------------------------------------------------------------------------")]
        public string planillaCierre {
            get {
                return ((string)(this["planillaCierre"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
##nmHotelLISTADO ARTICULOS EN STOCK
                                           ============================

  NUM      DESCRIPCIÓN                                         STOCK     CONSUMO     REPONER     STOCK GENERAL
===============================================================================================================\r\n")]
        public string listadoArtStock {
            get {
                return ((string)(this["listadoArtStock"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
                                            LISTADO DE ROPA CONSUMIDA
                                           ===========================

              CATEGORIA            FUNDAS   SABANAS   ACOLCHADOS   TOALLAS   TOALLONES   BATAS
              =================================================================================\r\n")]
        public string listadoRopaConsumida {
            get {
                return ((string)(this["listadoRopaConsumida"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\hotel\\")]
        public string pathHoteleria {
            get {
                return ((string)(this["pathHoteleria"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n          Fecha: ##FECHA Hora: ##HORA    Nro.Ticket: ##NRO\r\n          \r\n       " +
            "   Estado de Stock Lavadero\r\n                        En lavadero   Entregó   Dif" +
            "erencia    Retira    Saldo Final \\r\\n")]
        public string ticketLavadero {
            get {
                return ((string)(this["ticketLavadero"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\nFecha: ##FECHA Hora: ##HORA\\r\\nNro.Ticket: ##NRO\r\n-----------------------------" +
            "------\r\nMonto       Gasto\r\n-----------------------------------\\r\\n\r\n        ")]
        public string ticketGasto {
            get {
                return ((string)(this["ticketGasto"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\nFecha: ##FECHA\\r\\n\r\nHora Ing: ##HORA\\r\\n\r\n\r\nHabitación: ##NROHAB")]
        public string ticketAsignar {
            get {
                return ((string)(this["ticketAsignar"]));
            }
        }
    }
}
